FROM apache/airflow:3.3.1
RUN pip install --no-cache-dir --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-3.3.1/constraints-3.13.txt" "apache-airflow==3.3.1" apache-airflow-providers-databricks==7.18.1 simple-salesforce==1.12.10
